### ISSUE TITLE
May I have the ownership for the den crate?

### ISSUE THREAD

**Issue by stevefan1999-personal** [Icelk/agde#9]
Hi, I'm the founder of https://github.com/stevefan1999-personal/den, and I've noticed that you currently hold the `den` crate in crates.io. I hope this message finds you well. I'm reaching out because I'm interested in publishing documentation for my project, and having ownership of the `den` crate would greatly facilitate this process rather than having to rename the main CLI crate to `den-cli`. I was wondering if you'd be open to transferring ownership of the crate to me. This would allow me to maintain and update the crate with the latest information, documentation and also better publicity. I'd be more than happy to discuss this further if you have any questions or concerns. Your consideration in this matter would be greatly appreciated.

**Comment by Icelk** [comment]
Hi!
Sure, I think that should be possible. Allow me a few days to come up with a new name for my crate. Ur projects seems pretty cool.

**Comment by Icelk** [comment]
I think [dach](https://crates.io/crates/dach) is good, but I'll have to let it sink in.

**Comment by stevefan1999-personal** [comment]
Much appreciated. After that, please add me as an owner of den crate by using: https://doc.rust-lang.org/cargo/commands/cargo-owner.html

**Comment by Icelk** [comment]
An invite should be sent now :)

**Comment by Icelk** [comment]
Fixed with 8c4adbfa8

**Comment by stevefan1999-personal** [comment]
Thank you :)
